import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import "./globals.css";
import { CategoryProvider } from "./providers/CategoryContext";
import { TagProvider } from "./providers/TagContext";
import { ParentCategoryProvider } from "./providers/ParentCategoryContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <CategoryProvider>
          <TagProvider>
            <ParentCategoryProvider>{children}</ParentCategoryProvider>
          </TagProvider>
        </CategoryProvider>
      </body>
    </html>
  );
}
